### ISSUE TITLE
Installing Zeek on Windows.

### ISSUE THREAD

**Issue by asif48** [Abonnen/Malicious_TLS_Detection#1]
Apology for a very basic question because it is giving me tough time...

How can I run the command 
bro -r filename.pcap

Since I am not been able to install Zeek on windows.

The setup I have downloaded
1) https://www.zeek.org/download/index.html
2) Github
Both breaks during unzipped...

Does it is necessary to analyze the pcap using Zeek or any other tool will serve the same?
Plz suggests alternate tools of Zeek.
Plz guide

**Comment by Abonnen** [comment]
Zeek does not support windows, it only works on Linux or Mac. As for alternate tools, I think any netflow analysis software is okay, as long as you can extract the traffic features used for modeling.

**Comment by asif48** [comment]
thanks for the reply...

I have used Wireshark to extract the required files...

**Comment by asif48** [comment]
I have extracted the log files from zeek on linux....
thnaks
