### ISSUE TITLE
ipAddr,  infected or normal host IP address,  normal data set

### ISSUE THREAD

**Issue by asif48** [Abonnen/Malicious_TLS_Detection#2]
Plz guide regarding few queries...

1) What should be the IP address in IPAdr.txt since the IP addresses extracted from pcap are sometimes behaves as source and sometimes destination...
2) "In this project, the infected or normal host IP address has been already known." (Does it mean that IP address extracted from the pcap all are infected and my local host is the normal one?)
3) what should be the data in normal data set folder?

your help is appreciated...

**Comment by Abonnen** [comment]
1. IPAdr.txt is source IP addr.
2. It means that all netflow should be labeled as infected(malicious) or normal(benign), so you can do supervised ML.
3. Data in normal dataset folder looks same as infected ones (e.g. both contains pcap files and bro folder) and the only difference between them is the label.

**Comment by asif48** [comment]
thats great...

I will update you ...

**Comment by asif48** [comment]
Sir I have followed the above instructions. However, I am facing an issue as below...

![__main__](https://user-images.githubusercontent.com/7997380/65391478-14260100-dd83-11e9-8f15-40feb2caa554.png)

Error: I have tried by manually creating the "data_model" folder and adding "dataset-dataset0.csv" file but it fails again... 

**Little Background**
1) I have placed only my public IP Address (by google at whatsmy ip) in IPAdr.txt in the Malicious folder file as...
               Malicious 115.167.61.86 
2) I have placed just one data set in each Malicious and Normal folder as below...
3) I have placed the pcap file (traffic_analysis_test) in the malicious folder and the one of the CTU dataset file in normal folder (as a labeled data)...

The above config is correct? 

**Sir thanking for your cooperation.**

**Comment by Abonnen** [comment]
It seems that the config is correct, but I must remind you that the source code relys on `Zeek` and its logs, so if you use some other analysis tools, you might have to rewrite `feature_extract/analyze_log.py`

**Comment by asif48** [comment]
I have extracted logs from Bro on Linux and then transfer the logs to the project at windows...

Sir if you can send me its working copy? I am a student and I need it quite desperately....
 
Thanking for your cooperation!

**Comment by Abonnen** [comment]
Sorry, I didn't save my original dataset, but [CTU-dataset](https://mcfp.felk.cvut.cz/publicDatasets/) contains some extracted bro logs, you can use them.

**Comment by asif48** [comment]
Sir if you can help?

**Comment by asif48** [comment]
I have resolved the issue...
